CREATE TABLE "recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"ingredients" jsonb NOT NULL,
	"instructions" text NOT NULL,
	"categories" jsonb NOT NULL,
	"prep_time" integer,
	"cook_time" integer,
	"servings" integer,
	"image_url" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"user_id" varchar(256) NOT NULL
);
--> statement-breakpoint
CREATE INDEX "title_idx" ON "recipe" USING btree ("title");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "recipe" USING btree ("user_id");